routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');
Route::get('/catalog', 'Frontend\shop\CatalogController@index')->name('catalog');
Route::get('/checkout', 'Frontend\shop\CheckoutController@index')->name('checkout');
Route::get('/delivery', 'Frontend\shop\DeliveryController@index')->name('delivery');

Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');
Auth::routes();

Route::group(['as' => 'profile.', 'namespace' => 'Frontend', 'middleware' => ['auth']], function () {
    Route::get('/profile', 'ProfileController@index')->name('profile');

    // Promo Code
    Route::delete('promo-codes/destroy', 'PromoCodeController@massDestroy')->name('promo-codes.massDestroy');
    Route::resource('promo-codes', 'PromoCodeController');

    // Address
    Route::delete('addresses/destroy', 'AddressController@massDestroy')->name('addresses.massDestroy');
    Route::resource('addresses', 'AddressController');

    // Bonus
    Route::delete('bonus/destroy', 'BonusController@massDestroy')->name('bonus.massDestroy');
    Route::resource('bonus', 'BonusController');

    // User Event
    Route::delete('user-events/destroy', 'UserEventController@massDestroy')->name('user-events.massDestroy');
    Route::resource('user-events', 'UserEventController');

    // Profile
    Route::get('frontend/profile', 'ProfileController@index')->name('profile.index');
    Route::post('frontend/profile', 'ProfileController@update')->name('profile.update');
    Route::post('frontend/profile/destroy', 'ProfileController@destroy')->name('profile.destroy');
    Route::post('frontend/profile/password', 'ProfileController@password')->name('profile.password');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Category
    Route::delete('categories/destroy', 'CategoryController@massDestroy')->name('categories.massDestroy');
    Route::post('categories/media', 'CategoryController@storeMedia')->name('categories.storeMedia');
    Route::post('categories/ckmedia', 'CategoryController@storeCKEditorImages')->name('categories.storeCKEditorImages');
    Route::post('categories/parse-csv-import', 'CategoryController@parseCsvImport')->name('categories.parseCsvImport');
    Route::post('categories/process-csv-import', 'CategoryController@processCsvImport')->name('categories.processCsvImport');
    Route::resource('categories', 'CategoryController');

    // Event
    Route::delete('events/destroy', 'EventController@massDestroy')->name('events.massDestroy');
    Route::resource('events', 'EventController');

    // Color
    Route::delete('colors/destroy', 'ColorController@massDestroy')->name('colors.massDestroy');
    Route::resource('colors', 'ColorController');

    // Product
    Route::delete('products/destroy', 'ProductController@massDestroy')->name('products.massDestroy');
    Route::post('products/media', 'ProductController@storeMedia')->name('products.storeMedia');
    Route::post('products/ckmedia', 'ProductController@storeCKEditorImages')->name('products.storeCKEditorImages');
    Route::post('products/parse-csv-import', 'ProductController@parseCsvImport')->name('products.parseCsvImport');
    Route::post('products/process-csv-import', 'ProductController@processCsvImport')->name('products.processCsvImport');
    Route::resource('products', 'ProductController');

    // Tag
    Route::delete('tags/destroy', 'TagController@massDestroy')->name('tags.massDestroy');
    Route::resource('tags', 'TagController');

    // Promo Code
    Route::delete('promo-codes/destroy', 'PromoCodeController@massDestroy')->name('promo-codes.massDestroy');
    Route::resource('promo-codes', 'PromoCodeController');

    // Address
    Route::delete('addresses/destroy', 'AddressController@massDestroy')->name('addresses.massDestroy');
    Route::resource('addresses', 'AddressController');

    // Delivery Period
    Route::delete('delivery-periods/destroy', 'DeliveryPeriodController@massDestroy')->name('delivery-periods.massDestroy');
    Route::resource('delivery-periods', 'DeliveryPeriodController');

    // Bonus
    Route::delete('bonus/destroy', 'BonusController@massDestroy')->name('bonus.massDestroy');
    Route::resource('bonus', 'BonusController');

    // Offer
    Route::delete('offers/destroy', 'OfferController@massDestroy')->name('offers.massDestroy');
    Route::resource('offers', 'OfferController');

    // Total Offer
    Route::delete('total-offers/destroy', 'TotalOfferController@massDestroy')->name('total-offers.massDestroy');
    Route::resource('total-offers', 'TotalOfferController');

    // User Event
    Route::delete('user-events/destroy', 'UserEventController@massDestroy')->name('user-events.massDestroy');
    Route::resource('user-events', 'UserEventController');

    // Setting
    Route::delete('settings/destroy', 'SettingController@massDestroy')->name('settings.massDestroy');
    Route::post('settings/media', 'SettingController@storeMedia')->name('settings.storeMedia');
    Route::post('settings/ckmedia', 'SettingController@storeCKEditorImages')->name('settings.storeCKEditorImages');
    Route::resource('settings', 'SettingController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/TotalOffer.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TotalOffer extends Model
{
    use SoftDeletes;
    use HasFactory;

    public $table = 'total_offers';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'number',
        'summ',
        'is_constructor',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function offers()
    {
        return $this->belongsToMany(Offer::class);
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/TotalOfferController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTotalOfferRequest;
use App\Http\Requests\StoreTotalOfferRequest;
use App\Http\Requests\UpdateTotalOfferRequest;
use App\Models\Offer;
use App\Models\TotalOffer;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TotalOfferController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('total_offer_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $totalOffers = TotalOffer::with(['offers'])->get();

        return view('admin.totalOffers.index', compact('totalOffers'));
    }

    public function create()
    {
        abort_if(Gate::denies('total_offer_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $offers = Offer::pluck('name', 'id');

        return view('admin.totalOffers.create', compact('offers'));
    }

    public function store(StoreTotalOfferRequest $request)
    {
        $totalOffer = TotalOffer::create($request->all());
        $totalOffer->offers()->sync($request->input('offers', []));

        return redirect()->route('admin.total-offers.index');
    }

    public function edit(TotalOffer $totalOffer)
    {
        abort_if(Gate::denies('total_offer_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $offers = Offer::pluck('name', 'id');

        $totalOffer->load('offers');

        return view('admin.totalOffers.edit', compact('offers', 'totalOffer'));
    }

    public function update(UpdateTotalOfferRequest $request, TotalOffer $totalOffer)
    {
        $totalOffer->update($request->all());
        $totalOffer->offers()->sync($request->input('offers', []));

        return redirect()->route('admin.total-offers.index');
    }

    public function show(TotalOffer $totalOffer)
    {
        abort_if(Gate::denies('total_offer_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $totalOffer->load('offers');

        return view('admin.totalOffers.show', compact('totalOffer'));
    }

    public function destroy(TotalOffer $totalOffer)
    {
        abort_if(Gate::denies('total_offer_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $totalOffer->delete();

        return back();
    }

    public function massDestroy(MassDestroyTotalOfferRequest $request)
    {
        TotalOffer::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Frontend/shop/TotalOfferController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyTotalOfferRequest;
use App\Http\Requests\StoreTotalOfferRequest;
use App\Http\Requests\UpdateTotalOfferRequest;
use App\Models\Offer;
use App\Models\TotalOffer;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class TotalOfferController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('total_offer_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $totalOffers = TotalOffer::with(['offers'])->get();

        return view('frontend.totalOffers.index', compact('totalOffers'));
    }

    public function create()
    {
        abort_if(Gate::denies('total_offer_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $offers = Offer::pluck('name', 'id');

        return view('frontend.totalOffers.create', compact('offers'));
    }

    public function store(StoreTotalOfferRequest $request)
    {
        $totalOffer = TotalOffer::create($request->all());
        $totalOffer->offers()->sync($request->input('offers', []));

        return redirect()->route('frontend.total-offers.index');
    }

    public function edit(TotalOffer $totalOffer)
    {
        abort_if(Gate::denies('total_offer_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $offers = Offer::pluck('name', 'id');

        $totalOffer->load('offers');

        return view('frontend.totalOffers.edit', compact('offers', 'totalOffer'));
    }

    public function update(UpdateTotalOfferRequest $request, TotalOffer $totalOffer)
    {
        $totalOffer->update($request->all());
        $totalOffer->offers()->sync($request->input('offers', []));

        return redirect()->route('frontend.total-offers.index');
    }

    public function show(TotalOffer $totalOffer)
    {
        abort_if(Gate::denies('total_offer_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $totalOffer->load('offers');

        return view('frontend.totalOffers.show', compact('totalOffer'));
    }

    public function destroy(TotalOffer $totalOffer)
    {
        abort_if(Gate::denies('total_offer_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $totalOffer->delete();

        return back();
    }

    public function massDestroy(MassDestroyTotalOfferRequest $request)
    {
        TotalOffer::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/totalOffers/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.totalOffer.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.total-offers.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name">{{ trans('cruds.totalOffer.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}">
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="offers">{{ trans('cruds.totalOffer.fields.offers') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('offers') ? 'is-invalid' : '' }}" name="offers[]" id="offers" multiple required>
                    @foreach($offers as $id => $offer)
                        <option value="{{ $id }}" {{ in_array($id, old('offers', [])) ? 'selected' : '' }}>{{ $offer }}</option>
                    @endforeach
                </select>
                @if($errors->has('offers'))
                    <div class="invalid-feedback">
                        {{ $errors->first('offers') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.offers_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="number">{{ trans('cruds.totalOffer.fields.number') }}</label>
                <input class="form-control {{ $errors->has('number') ? 'is-invalid' : '' }}" type="number" name="number" id="number" value="{{ old('number', '1') }}" step="1">
                @if($errors->has('number'))
                    <div class="invalid-feedback">
                        {{ $errors->first('number') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.number_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="summ">{{ trans('cruds.totalOffer.fields.summ') }}</label>
                <input class="form-control {{ $errors->has('summ') ? 'is-invalid' : '' }}" type="number" name="summ" id="summ" value="{{ old('summ', '') }}" step="1">
                @if($errors->has('summ'))
                    <div class="invalid-feedback">
                        {{ $errors->first('summ') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.summ_helper') }}</span>
            </div>
            <div class="form-group">
                <div class="form-check {{ $errors->has('is_constructor') ? 'is-invalid' : '' }}">
                    <input class="form-check-input" type="checkbox" name="is_constructor" id="is_constructor" value="1" required {{ old('is_constructor', 0) == 1 ? 'checked' : '' }}>
                    <label class="required form-check-label" for="is_constructor">{{ trans('cruds.totalOffer.fields.is_constructor') }}</label>
                </div>
                @if($errors->has('is_constructor'))
                    <div class="invalid-feedback">
                        {{ $errors->first('is_constructor') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.is_constructor_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/totalOffers/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.totalOffer.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.total-offers.update", [$totalOffer->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="name">{{ trans('cruds.totalOffer.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $totalOffer->name) }}">
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="offers">{{ trans('cruds.totalOffer.fields.offers') }}</label>
                <div style="padding-bottom: 4px">
                    <span class="btn btn-info btn-xs select-all" style="border-radius: 0">{{ trans('global.select_all') }}</span>
                    <span class="btn btn-info btn-xs deselect-all" style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                </div>
                <select class="form-control select2 {{ $errors->has('offers') ? 'is-invalid' : '' }}" name="offers[]" id="offers" multiple required>
                    @foreach($offers as $id => $offer)
                        <option value="{{ $id }}" {{ (in_array($id, old('offers', [])) || $totalOffer->offers->contains($id)) ? 'selected' : '' }}>{{ $offer }}</option>
                    @endforeach
                </select>
                @if($errors->has('offers'))
                    <div class="invalid-feedback">
                        {{ $errors->first('offers') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.offers_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="number">{{ trans('cruds.totalOffer.fields.number') }}</label>
                <input class="form-control {{ $errors->has('number') ? 'is-invalid' : '' }}" type="number" name="number" id="number" value="{{ old('number', $totalOffer->number) }}" step="1">
                @if($errors->has('number'))
                    <div class="invalid-feedback">
                        {{ $errors->first('number') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.number_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="summ">{{ trans('cruds.totalOffer.fields.summ') }}</label>
                <input class="form-control {{ $errors->has('summ') ? 'is-invalid' : '' }}" type="number" name="summ" id="summ" value="{{ old('summ', $totalOffer->summ) }}" step="1">
                @if($errors->has('summ'))
                    <div class="invalid-feedback">
                        {{ $errors->first('summ') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.summ_helper') }}</span>
            </div>
            <div class="form-group">
                <div class="form-check {{ $errors->has('is_constructor') ? 'is-invalid' : '' }}">
                    <input class="form-check-input" type="checkbox" name="is_constructor" id="is_constructor" value="1" {{ $totalOffer->is_constructor || old('is_constructor', 0) === 1 ? 'checked' : '' }} required>
                    <label class="required form-check-label" for="is_constructor">{{ trans('cruds.totalOffer.fields.is_constructor') }}</label>
                </div>
                @if($errors->has('is_constructor'))
                    <div class="invalid-feedback">
                        {{ $errors->first('is_constructor') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.totalOffer.fields.is_constructor_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/totalOffers/index.blade.php
@extends('layouts.admin')
@section('content')
@can('total_offer_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.total-offers.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.totalOffer.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.totalOffer.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-TotalOffer">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.totalOffer.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.totalOffer.fields.name') }}
                        </th>
                        <th>
                            {{ trans('cruds.totalOffer.fields.offers') }}
                        </th>
                        <th>
                            {{ trans('cruds.totalOffer.fields.number') }}
                        </th>
                        <th>
                            {{ trans('cruds.totalOffer.fields.summ') }}
                        </th>
                        <th>
                            {{ trans('cruds.totalOffer.fields.is_constructor') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($totalOffers as $key => $totalOffer)
                        <tr data-entry-id="{{ $totalOffer->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $totalOffer->id ?? '' }}
                            </td>
                            <td>
                                {{ $totalOffer->name ?? '' }}
                            </td>
                            <td>
                                @foreach($totalOffer->offers as $key => $item)
                                    <span class="badge badge-info">{{ $item->name }}</span>
                                @endforeach
                            </td>
                            <td>
                                {{ $totalOffer->number ?? '' }}
                            </td>
                            <td>
                                {{ $totalOffer->summ ?? '' }}
                            </td>
                            <td>
                                <span style="display:none">{{ $totalOffer->is_constructor ?? '' }}</span>
                                <input type="checkbox" disabled="disabled" {{ $totalOffer->is_constructor ? 'checked' : '' }}>
                            </td>
                            <td>
                                @can('total_offer_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.total-offers.show', $totalOffer->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('total_offer_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.total-offers.edit', $totalOffer->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('total_offer_delete')
                                    <form action="{{ route('admin.total-offers.destroy', $totalOffer->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('total_offer_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.total-offers.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-TotalOffer:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/totalOffers/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.totalOffer.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.total-offers.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.totalOffer.fields.id') }}
                        </th>
                        <td>
                            {{ $totalOffer->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.totalOffer.fields.name') }}
                        </th>
                        <td>
                            {{ $totalOffer->name }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.totalOffer.fields.offers') }}
                        </th>
                        <td>
                            @foreach($totalOffer->offers as $key => $offers)
                                <span class="label label-info">{{ $offers->name }}</span>
                            @endforeach
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.totalOffer.fields.number') }}
                        </th>
                        <td>
                            {{ $totalOffer->number }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.totalOffer.fields.summ') }}
                        </th>
                        <td>
                            {{ $totalOffer->summ }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.totalOffer.fields.is_constructor') }}
                        </th>
                        <td>
                            <input type="checkbox" disabled="disabled" {{ $totalOffer->is_constructor ? 'checked' : '' }}>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.total-offers.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection