routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');
Route::get('/catalog', 'Frontend\shop\CatalogController@index')->name('catalog');
Route::get('/checkout', 'Frontend\shop\CheckoutController@index')->name('checkout');
Route::get('/delivery', 'Frontend\shop\DeliveryController@index')->name('delivery');

Route::get('userVerification/{token}', 'UserVerificationController@approve')->name('userVerification');
Auth::routes();

Route::group(['as' => 'profile.', 'namespace' => 'Frontend', 'middleware' => ['auth']], function () {
    Route::get('/profile', 'ProfileController@index')->name('profile');

    // Promo Code
    Route::delete('promo-codes/destroy', 'PromoCodeController@massDestroy')->name('promo-codes.massDestroy');
    Route::resource('promo-codes', 'PromoCodeController');

    // Address
    Route::delete('addresses/destroy', 'AddressController@massDestroy')->name('addresses.massDestroy');
    Route::resource('addresses', 'AddressController');

    // Bonus
    Route::delete('bonus/destroy', 'BonusController@massDestroy')->name('bonus.massDestroy');
    Route::resource('bonus', 'BonusController');

    // User Event
    Route::delete('user-events/destroy', 'UserEventController@massDestroy')->name('user-events.massDestroy');
    Route::resource('user-events', 'UserEventController');

    // Profile
    Route::get('frontend/profile', 'ProfileController@index')->name('profile.index');
    Route::post('frontend/profile', 'ProfileController@update')->name('profile.update');
    Route::post('frontend/profile/destroy', 'ProfileController@destroy')->name('profile.destroy');
    Route::post('frontend/profile/password', 'ProfileController@password')->name('profile.password');
});

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::post('users/parse-csv-import', 'UsersController@parseCsvImport')->name('users.parseCsvImport');
    Route::post('users/process-csv-import', 'UsersController@processCsvImport')->name('users.processCsvImport');
    Route::resource('users', 'UsersController');

    // Category
    Route::delete('categories/destroy', 'CategoryController@massDestroy')->name('categories.massDestroy');
    Route::post('categories/media', 'CategoryController@storeMedia')->name('categories.storeMedia');
    Route::post('categories/ckmedia', 'CategoryController@storeCKEditorImages')->name('categories.storeCKEditorImages');
    Route::post('categories/parse-csv-import', 'CategoryController@parseCsvImport')->name('categories.parseCsvImport');
    Route::post('categories/process-csv-import', 'CategoryController@processCsvImport')->name('categories.processCsvImport');
    Route::resource('categories', 'CategoryController');

    // Event
    Route::delete('events/destroy', 'EventController@massDestroy')->name('events.massDestroy');
    Route::resource('events', 'EventController');

    // Color
    Route::delete('colors/destroy', 'ColorController@massDestroy')->name('colors.massDestroy');
    Route::resource('colors', 'ColorController');

    // Product
    Route::delete('products/destroy', 'ProductController@massDestroy')->name('products.massDestroy');
    Route::post('products/media', 'ProductController@storeMedia')->name('products.storeMedia');
    Route::post('products/ckmedia', 'ProductController@storeCKEditorImages')->name('products.storeCKEditorImages');
    Route::post('products/parse-csv-import', 'ProductController@parseCsvImport')->name('products.parseCsvImport');
    Route::post('products/process-csv-import', 'ProductController@processCsvImport')->name('products.processCsvImport');
    Route::resource('products', 'ProductController');

    // Tag
    Route::delete('tags/destroy', 'TagController@massDestroy')->name('tags.massDestroy');
    Route::resource('tags', 'TagController');

    // Promo Code
    Route::delete('promo-codes/destroy', 'PromoCodeController@massDestroy')->name('promo-codes.massDestroy');
    Route::resource('promo-codes', 'PromoCodeController');

    // Address
    Route::delete('addresses/destroy', 'AddressController@massDestroy')->name('addresses.massDestroy');
    Route::resource('addresses', 'AddressController');

    // Delivery Period
    Route::delete('delivery-periods/destroy', 'DeliveryPeriodController@massDestroy')->name('delivery-periods.massDestroy');
    Route::resource('delivery-periods', 'DeliveryPeriodController');

    // Bonus
    Route::delete('bonus/destroy', 'BonusController@massDestroy')->name('bonus.massDestroy');
    Route::resource('bonus', 'BonusController');

    // Offer
    Route::delete('offers/destroy', 'OfferController@massDestroy')->name('offers.massDestroy');
    Route::resource('offers', 'OfferController');

    // Total Offer
    Route::delete('total-offers/destroy', 'TotalOfferController@massDestroy')->name('total-offers.massDestroy');
    Route::resource('total-offers', 'TotalOfferController');

    // User Event
    Route::delete('user-events/destroy', 'UserEventController@massDestroy')->name('user-events.massDestroy');
    Route::resource('user-events', 'UserEventController');

    // Setting
    Route::delete('settings/destroy', 'SettingController@massDestroy')->name('settings.massDestroy');
    Route::post('settings/media', 'SettingController@storeMedia')->name('settings.storeMedia');
    Route::post('settings/ckmedia', 'SettingController@storeCKEditorImages')->name('settings.storeCKEditorImages');
    Route::resource('settings', 'SettingController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});

app/Models/PromoCode.php
<?php

namespace App\Models;

use \DateTimeInterface;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PromoCode extends Model
{
    use SoftDeletes;
    use HasFactory;

    public const TYPE_SELECT = [
        'summ'    => 'Сумма',
        'percent' => 'Проценты',
    ];

    public $table = 'promo_codes';

    protected $dates = [
        'active_until',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'code',
        'type',
        'summ',
        'percent',
        'is_active',
        'active_until',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function getActiveUntilAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setActiveUntilAttribute($value)
    {
        $this->attributes['active_until'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }
}

app/Http/Controllers/Admin/PromoCodeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyPromoCodeRequest;
use App\Http\Requests\StorePromoCodeRequest;
use App\Http\Requests\UpdatePromoCodeRequest;
use App\Models\PromoCode;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class PromoCodeController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('promo_code_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $promoCodes = PromoCode::all();

        return view('admin.promoCodes.index', compact('promoCodes'));
    }

    public function create()
    {
        abort_if(Gate::denies('promo_code_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.promoCodes.create');
    }

    public function store(StorePromoCodeRequest $request)
    {
        $promoCode = PromoCode::create($request->all());

        return redirect()->route('admin.promo-codes.index');
    }

    public function edit(PromoCode $promoCode)
    {
        abort_if(Gate::denies('promo_code_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.promoCodes.edit', compact('promoCode'));
    }

    public function update(UpdatePromoCodeRequest $request, PromoCode $promoCode)
    {
        $promoCode->update($request->all());

        return redirect()->route('admin.promo-codes.index');
    }

    public function show(PromoCode $promoCode)
    {
        abort_if(Gate::denies('promo_code_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.promoCodes.show', compact('promoCode'));
    }

    public function destroy(PromoCode $promoCode)
    {
        abort_if(Gate::denies('promo_code_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $promoCode->delete();

        return back();
    }

    public function massDestroy(MassDestroyPromoCodeRequest $request)
    {
        PromoCode::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Frontend/shop/PromoCodeController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyPromoCodeRequest;
use App\Http\Requests\StorePromoCodeRequest;
use App\Http\Requests\UpdatePromoCodeRequest;
use App\Models\PromoCode;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class PromoCodeController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('promo_code_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $promoCodes = PromoCode::all();

        return view('frontend.promoCodes.index', compact('promoCodes'));
    }

    public function create()
    {
        abort_if(Gate::denies('promo_code_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.promoCodes.create');
    }

    public function store(StorePromoCodeRequest $request)
    {
        $promoCode = PromoCode::create($request->all());

        return redirect()->route('frontend.promo-codes.index');
    }

    public function edit(PromoCode $promoCode)
    {
        abort_if(Gate::denies('promo_code_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.promoCodes.edit', compact('promoCode'));
    }

    public function update(UpdatePromoCodeRequest $request, PromoCode $promoCode)
    {
        $promoCode->update($request->all());

        return redirect()->route('frontend.promo-codes.index');
    }

    public function show(PromoCode $promoCode)
    {
        abort_if(Gate::denies('promo_code_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.promoCodes.show', compact('promoCode'));
    }

    public function destroy(PromoCode $promoCode)
    {
        abort_if(Gate::denies('promo_code_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $promoCode->delete();

        return back();
    }

    public function massDestroy(MassDestroyPromoCodeRequest $request)
    {
        PromoCode::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/promoCodes/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.promoCode.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.promo-codes.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label class="required" for="code">{{ trans('cruds.promoCode.fields.code') }}</label>
                <input class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" type="text" name="code" id="code" value="{{ old('code', '') }}" required>
                @if($errors->has('code'))
                    <div class="invalid-feedback">
                        {{ $errors->first('code') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.code_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.promoCode.fields.type') }}</label>
                <select class="form-control {{ $errors->has('type') ? 'is-invalid' : '' }}" name="type" id="type" required>
                    <option value disabled {{ old('type', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\PromoCode::TYPE_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('type', 'summ') === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('type'))
                    <div class="invalid-feedback">
                        {{ $errors->first('type') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.type_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="summ">{{ trans('cruds.promoCode.fields.summ') }}</label>
                <input class="form-control {{ $errors->has('summ') ? 'is-invalid' : '' }}" type="number" name="summ" id="summ" value="{{ old('summ', '') }}" step="1">
                @if($errors->has('summ'))
                    <div class="invalid-feedback">
                        {{ $errors->first('summ') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.summ_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="percent">{{ trans('cruds.promoCode.fields.percent') }}</label>
                <input class="form-control {{ $errors->has('percent') ? 'is-invalid' : '' }}" type="number" name="percent" id="percent" value="{{ old('percent', '') }}" step="1">
                @if($errors->has('percent'))
                    <div class="invalid-feedback">
                        {{ $errors->first('percent') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.percent_helper') }}</span>
            </div>
            <div class="form-group">
                <div class="form-check {{ $errors->has('is_active') ? 'is-invalid' : '' }}">
                    <input class="form-check-input" type="checkbox" name="is_active" id="is_active" value="1" required {{ old('is_active', 0) == 1 || old('is_active') === null ? 'checked' : '' }}>
                    <label class="required form-check-label" for="is_active">{{ trans('cruds.promoCode.fields.is_active') }}</label>
                </div>
                @if($errors->has('is_active'))
                    <div class="invalid-feedback">
                        {{ $errors->first('is_active') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.is_active_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="active_until">{{ trans('cruds.promoCode.fields.active_until') }}</label>
                <input class="form-control date {{ $errors->has('active_until') ? 'is-invalid' : '' }}" type="text" name="active_until" id="active_until" value="{{ old('active_until') }}" required>
                @if($errors->has('active_until'))
                    <div class="invalid-feedback">
                        {{ $errors->first('active_until') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.active_until_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/promoCodes/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.promoCode.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.promo-codes.update", [$promoCode->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label class="required" for="code">{{ trans('cruds.promoCode.fields.code') }}</label>
                <input class="form-control {{ $errors->has('code') ? 'is-invalid' : '' }}" type="text" name="code" id="code" value="{{ old('code', $promoCode->code) }}" required>
                @if($errors->has('code'))
                    <div class="invalid-feedback">
                        {{ $errors->first('code') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.code_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required">{{ trans('cruds.promoCode.fields.type') }}</label>
                <select class="form-control {{ $errors->has('type') ? 'is-invalid' : '' }}" name="type" id="type" required>
                    <option value disabled {{ old('type', null) === null ? 'selected' : '' }}>{{ trans('global.pleaseSelect') }}</option>
                    @foreach(App\Models\PromoCode::TYPE_SELECT as $key => $label)
                        <option value="{{ $key }}" {{ old('type', $promoCode->type) === (string) $key ? 'selected' : '' }}>{{ $label }}</option>
                    @endforeach
                </select>
                @if($errors->has('type'))
                    <div class="invalid-feedback">
                        {{ $errors->first('type') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.type_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="summ">{{ trans('cruds.promoCode.fields.summ') }}</label>
                <input class="form-control {{ $errors->has('summ') ? 'is-invalid' : '' }}" type="number" name="summ" id="summ" value="{{ old('summ', $promoCode->summ) }}" step="1">
                @if($errors->has('summ'))
                    <div class="invalid-feedback">
                        {{ $errors->first('summ') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.summ_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="percent">{{ trans('cruds.promoCode.fields.percent') }}</label>
                <input class="form-control {{ $errors->has('percent') ? 'is-invalid' : '' }}" type="number" name="percent" id="percent" value="{{ old('percent', $promoCode->percent) }}" step="1">
                @if($errors->has('percent'))
                    <div class="invalid-feedback">
                        {{ $errors->first('percent') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.percent_helper') }}</span>
            </div>
            <div class="form-group">
                <div class="form-check {{ $errors->has('is_active') ? 'is-invalid' : '' }}">
                    <input class="form-check-input" type="checkbox" name="is_active" id="is_active" value="1" {{ $promoCode->is_active || old('is_active', 0) === 1 ? 'checked' : '' }} required>
                    <label class="required form-check-label" for="is_active">{{ trans('cruds.promoCode.fields.is_active') }}</label>
                </div>
                @if($errors->has('is_active'))
                    <div class="invalid-feedback">
                        {{ $errors->first('is_active') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.is_active_helper') }}</span>
            </div>
            <div class="form-group">
                <label class="required" for="active_until">{{ trans('cruds.promoCode.fields.active_until') }}</label>
                <input class="form-control date {{ $errors->has('active_until') ? 'is-invalid' : '' }}" type="text" name="active_until" id="active_until" value="{{ old('active_until', $promoCode->active_until) }}" required>
                @if($errors->has('active_until'))
                    <div class="invalid-feedback">
                        {{ $errors->first('active_until') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.promoCode.fields.active_until_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/promoCodes/index.blade.php
@extends('layouts.admin')
@section('content')
@can('promo_code_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.promo-codes.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.promoCode.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.promoCode.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-PromoCode">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.promoCode.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.promoCode.fields.code') }}
                        </th>
                        <th>
                            {{ trans('cruds.promoCode.fields.type') }}
                        </th>
                        <th>
                            {{ trans('cruds.promoCode.fields.summ') }}
                        </th>
                        <th>
                            {{ trans('cruds.promoCode.fields.percent') }}
                        </th>
                        <th>
                            {{ trans('cruds.promoCode.fields.is_active') }}
                        </th>
                        <th>
                            {{ trans('cruds.promoCode.fields.active_until') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($promoCodes as $key => $promoCode)
                        <tr data-entry-id="{{ $promoCode->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $promoCode->id ?? '' }}
                            </td>
                            <td>
                                {{ $promoCode->code ?? '' }}
                            </td>
                            <td>
                                {{ App\Models\PromoCode::TYPE_SELECT[$promoCode->type] ?? '' }}
                            </td>
                            <td>
                                {{ $promoCode->summ ?? '' }}
                            </td>
                            <td>
                                {{ $promoCode->percent ?? '' }}
                            </td>
                            <td>
                                <span style="display:none">{{ $promoCode->is_active ?? '' }}</span>
                                <input type="checkbox" disabled="disabled" {{ $promoCode->is_active ? 'checked' : '' }}>
                            </td>
                            <td>
                                {{ $promoCode->active_until ?? '' }}
                            </td>
                            <td>
                                @can('promo_code_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.promo-codes.show', $promoCode->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('promo_code_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.promo-codes.edit', $promoCode->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('promo_code_delete')
                                    <form action="{{ route('admin.promo-codes.destroy', $promoCode->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('promo_code_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.promo-codes.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-PromoCode:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/promoCodes/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.promoCode.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.promo-codes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.promoCode.fields.id') }}
                        </th>
                        <td>
                            {{ $promoCode->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.promoCode.fields.code') }}
                        </th>
                        <td>
                            {{ $promoCode->code }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.promoCode.fields.type') }}
                        </th>
                        <td>
                            {{ App\Models\PromoCode::TYPE_SELECT[$promoCode->type] ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.promoCode.fields.summ') }}
                        </th>
                        <td>
                            {{ $promoCode->summ }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.promoCode.fields.percent') }}
                        </th>
                        <td>
                            {{ $promoCode->percent }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.promoCode.fields.is_active') }}
                        </th>
                        <td>
                            <input type="checkbox" disabled="disabled" {{ $promoCode->is_active ? 'checked' : '' }}>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.promoCode.fields.active_until') }}
                        </th>
                        <td>
                            {{ $promoCode->active_until }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.promo-codes.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection